### ISSUE TITLE
Create Github Actions for g2-sdk-python-next

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/sz-sdk-python#39]
Create GitHub actions that do: 

- [x] **Code coverage:** `pytest` `py-cov-action/python-coverage-comment-action`
- [x] **Code format checking:** `flake8`, `black`, `isort`
- [x] **Security checking:** `bandit` - (our code) `safety` & `pip-audit` - (third party dependency scanning)
- [x] **Static analysis:** `mypy`
- [x] **Syntax checking:** `pylint`
- [x] **Unit testing:** `pytest`

### References

- https://github.com/senzing-garage/garage-roadmap/issues/6

**Comment by kernelsam** [comment]
Closing this as completed. Opened 2 follow up tasks:
- https://github.com/senzing-garage/sz-sdk-python/issues/59 
   - This is currently blocked by  coverage errors. Once those are resolved by dev this can be implemented. 
- https://github.com/senzing-garage/sz-sdk-python/issues/58
  - This will be implemented once the repository is at a stable point and dev no longer needs to generate docs as frequently.
